<!DOCTYPE html>
<html>
<head>
    <title>My Blog</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header> <h1>My Blog</h1> <nav> <ul> <li><a href="#">Home</a></li> <li><a href="#">About</a></li> <li><a href="#">Contact</a></li> </ul> </nav> </header>
    <main>
        <article>
            <header>
                <h2>My First Post</h2>
                <p>By Jane Doe, on March 8th, 2021</p>
            </header>
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu justo nec orci ullamcorper blandit. Aliquam vitae enim consectetur, pretium quam in, finibus ex. Nunc id ligula pretium, gravida tellus vitae, accumsan tellus. Ut venenatis turpis ut venenatis pretium. Integer fringilla vitae sapien vel placerat. Donec scelerisque quam ut purus lobortis sodales. Duis in rutrum dui. Etiam vitae quam ut neque aliquam fermentum vel ut purus.</p>
            <p>Ut luctus malesuada nulla vitae consectetur. Donec bibendum scelerisque velit, sit amet auctor leo congue id. Sed sed vehicula odio. Vivamus euismod magna leo, nec malesuada ipsum ullamcorper nec. Sed vel mauris eu risus eleifend lacinia. Curabitur nec arcu sed sem hendrerit varius vel vitae magna. </p>
            <footer>
                <p>Tags: <a href="#">personal</a>, <a href="#">thoughts</a></p>
            </footer>
        </article>

        <article>
            <header>
                <h2>My Second Post</h2>
                <p>By Jane Doe, on March 15th, 2021</p>
            </header>
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu justo nec orci ullamcorper blandit. Aliquam vitae enim consectetur, pretium quam in, finibus ex. Nunc id ligula pretium, gravida tellus vitae, accumsan tellus. Ut venenatis turpis ut venenatis pretium. Integer fringilla vitae sapien vel placerat. Donec scelerisque quam ut purus lobortis sodales. Duis in rutrum dui. Etiam vitae quam ut neque aliquam fermentum vel ut purus.</p>
            <p>Ut luctus malesuada nulla vitae consectetur. Donec bibendum scelerisque velit, sit amet auctor leo congue id. Sed sed vehicula odio. Vivamus euismod magna leo, nec malesuada ipsum ullamcorper nec. Sed vel mauris eu risus eleifend lacinia. Curabitur nec arcu sed sem hendrerit varius vel vitae magna. </p>
            <footer>
                <p>Tags: <a href="#">personal</a>, <a href="#">travel</a></p>
            </footer>
        </article>
    </main>

    <footer>
        <p>&copy; 2021 My Blog</p>
    </footer>
</body>
</html>
